version: "3.9"

services:
  freepbx:
    build:
      context: .
      dockerfile: freepbx/Dockerfile
    container_name: freepbx17
    depends_on:
      - mariadb
    ports:
      - "8080:80"
      - "8443:443"
      - "5060:5060/udp"
      - "5160:5160/udp"
      - "18000-18100:18000-18100/udp"
    volumes:
      - freepbx_data:/etc/asterisk
      - logs:/var/log/asterisk
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=freepbx
      - MYSQL_PASSWORD=freepbxpass
      - MYSQL_DATABASE=asterisk
    restart: unless-stopped

  mariadb:
    image: mariadb:10.5
    container_name: freepbx_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=freepbxpass
      - MYSQL_DATABASE=asterisk
      - MYSQL_USER=freepbx
      - MYSQL_PASSWORD=freepbxpass
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  freepbx_data:
  logs:
  db_data:
